class Linha():
    def __init__(self,cc, loc,nome,tensaoodi,odi,tipo,ti,cm1,cm2,cm3,uc,a1,a2,a3,a4,a5,a6,uar,bay,tag,qtd,
                un,ano,fabr,inst,modelo,serie,tensao,fase,desc):
        self.cc = cc,
        self.loc = loc,
        self.nome = nome,
        self.tensaoodi = tensaoodi,
        self.odi = odi,
        self.tipo = tipo,
        self.ti = ti,
        self.cm1 = cm1,
        self.cm2 = cm2,
        self.cm3 = cm3,
        self.uc = uc,
        self.a1 = a1,
        self.a2 = a2,
        self.a3 = a3,
        self.a4 = a4,
        self.a5 = a5,
        self.a6 = a6,
        self.uar = uar,
        self.bay = bay,
        self.tag = tag,
        self.qtd = qtd,
        self.un = un,
        self.ano = ano,
        self.fabr = fabr,
        self.inst = inst,
        self.modelo = modelo,
        self.serie = serie,
        self.tensao = tensao,
        self.fase = fase,
        self.desc = desc,

# base completa (comentada pois nesse momento iremos gerar apenas um modelo com as linhas que precisamos)
# base_modelo = [
#     "IDUC-ID","DIGITO SEQUENCIAL","DATA INVENTÁRIO","CONTRATO DE CONCESSÃO",
#     "LOCALIZAÇÃO","NOME DA ODI","TENSÃO","NUMERO DA ODI","TIPO DA SE","TI",
#     "DESCRIÇÃO TI","CM - DIGITO 1","SIGLA CM1","DESCRIÇÃO LOCAL DE INSTALAÇÃO",
#     "CM - DIGITO 2","SIGLA CM2","DESCRIÇÃO / COMPOSIÇÃO",
#     "CM - DIGITO 3","SIGLA CM3","DESCRIÇÃO ARRANJO FÍSICO",
#     "UC","DESCRIÇÃO UC","UC+A1","DESCRIÇÃO UC+A1","CM","TUC",
#     "A1","A2","A3","A4","A5","A6","ATRIBUTOS",
#     "TABELA A2","TABELA A3","TABELA A4","TABELA A5","TABELA A6",
#     "DADOS ATRIBUTO 2","DADOS ATRIBUTO 3","DADOS ATRIBUTO 4","DADOS ATRIBUTO 5","DADOS ATRIBUTO 6",
#     "CODIGO DA UAR","UC+UAR","DESCRIÇÃO UAR","CODIFICAÇÃO MCPSE","IDUC","BAY/LOCALIZAÇÃO",
#     "MODULO SIGET","NUMERO OPERACIONAL","NOME OPERACIONAL","POSIÇÃO / TAG","QUANTIDADE",
#     "UNIDADE","ANO DE FABRICAÇÃO","FABRICANTE","LOCAL DE INSTALAÇÃO","MODELO / TIPO","NR SÉRIE",
#     "TENSÃO NOMINAL","FASE","DESCRIÇÃO DO EQUIPAMENTO","ENTRADA DE OPERAÇÃO","DATA DE IMOBILIZAÇÃO",
#     "TAXA DE DEPRECIAÇÃO","VU - VIDA UTIL","FOTO 1","FOTO 2","FOTO 3"
# ]